import { Consonant } from './consonant';

export const CONSONANTS: Consonant[] = [
 {id: 1, character: "ก", "roman": "go gai", charclass: "m" },
 {id: 2, character: "ข", "roman": "kho khai", charclass: "h" },
 {id: 3, character: "ฃ", "roman": "kho khuat",  charclass: "h" },
 {id: 4, character: "ค", "roman": "kho khwai", charclass: "l" },
 {id: 5, character: "ฅ", "roman": "kho khon", charclass: "l" },
 {id: 6, character: "ฆ", "roman": "kho rakhang", charclass: "l" },
 {id: 7, character: "ง", "roman": "ngo ngu", charclass: "l" },
 {id: 8, character: "จ", "roman": "cho chan", charclass: "m" },
 {id: 9, character: "ฉ", "roman": "cho ching", charclass: "h" },
 {id: 10, character: "ช", "roman": "cho chang", charclass: "l" },
 {id: 11, character: "ซ", "roman": "so so", charclass: "l" },
 {id: 12, character: "ฌ", "roman": "cho choe", charclass: "l" },
 {id: 13, character: "ญ", "roman": "yo ying", charclass: "l" },
 {id: 14, character: "ฎ", "roman": "do chada", charclass: "m" },
 {id: 15, character: "ฏ", "roman": "dto patak", charclass: "m" },
 {id: 16, character: "ฐ", "roman": "tho than", charclass: "h" },
 {id: 17, character: "ฑ", "roman": "tho nangmontho", charclass: "l" },
 {id: 18, character: "ฒ", "roman": "tho puthao", charclass: "l" },
 {id: 19, character: "ณ", "roman": "no nen", charclass: "l" },
 {id: 20, character: "ด", "roman": "do dek", charclass: "m" },
 {id: 21, character: "ต", "roman": "dto tao", charclass: "m" },
 {id: 22, character: "ถ", "roman": "tho thung", charclass: "h" },
 {id: 23, character: "ท", "roman": "tho thahan", charclass: "l" },
 {id: 24, character: "ธ", "roman": "tho thong", charclass: "l" },
 {id: 25, character: "น", "roman": "no nu", charclass: "l" },
 {id: 26, character: "บ", "roman": "bo baimai", charclass: "m" },
 {id: 27, character: "ป", "roman": "po pla", charclass: "m" },
 {id: 28, character: "ผ", "roman": "pho phueng", charclass: "h" },
 {id: 29, character: "ฝ", "roman": "fo fa", charclass: "h" },
 {id: 30, character: "พ", "roman": "pho phan", charclass: "l" },
 {id: 31, character: "ฟ", "roman": "fo fan", charclass: "l" },
 {id: 32, character: "ภ", "roman": "pho samphao", charclass: "l" },
 {id: 33, character: "ม", "roman": "mo ma", charclass: "l" },
 {id: 34, character: "ย", "roman": "yo yak", charclass: "l" },
 {id: 35, character: "ร", "roman": "ro ruea", charclass: "l" },
 {id: 36, character: "ล", "roman": "lo ling", charclass: "l" },
 {id: 37, character: "ว", "roman": "wo waen", charclass: "l" },
 {id: 38, character: "ศ", "roman": "so sala", charclass: "h" },
 {id: 39, character: "ษ", "roman": "so ruesi", charclass: "h" },
 {id: 40, character: "ส", "roman": "so suea", charclass: "h" },
 {id: 41, character: "ห", "roman": "ho hip", charclass: "h" },
 {id: 42, character: "ฬ", "roman": "lo chula", charclass: "l" },
 {id: 43, character: "อ", "roman": "o ang", charclass: "m" },
 {id: 44, character: "ฮ", "roman": "ho nokhug", charclass: "l" }
];
