import { Consonant } from './consonant';

export const CONSONANTS: Consonant[] = [
 {id: 1, character: "ก", "phonetic": "kɔː kàj", "roman": "go gai", charclass: "m" },
 {id: 2, character: "ข", "phonetic": "kʰɔ̌ː kʰàj", "roman": "kho khai", charclass: "h" },
 {id: 3, character: "ฃ", "phonetic": "kʰɔ̌ː kʰùat", "roman": "kho khuat",  charclass: "h" },
 {id: 4, character: "ค", "phonetic": "kʰɔː kʰwaːj", "roman": "kho khwai", charclass: "l" },
 {id: 5, character: "ฅ", "phonetic": "kʰɔː kʰon", "roman": "kho khon", charclass: "l" },
 {id: 6, character: "ฆ", "phonetic": "kʰɔː rákʰaŋ", "roman": "kho rakhang", charclass: "l" },
 {id: 7, character: "ง", "phonetic": "ŋɔː ŋuː", "roman": "ngo ngu", charclass: "l" },
 {id: 8, character: "จ", "phonetic": "ʨɔː ʨaːn", "roman": "cho chan", charclass: "m" },
 {id: 9, character: "ฉ", "phonetic": "ʨʰɔ̌ː ʨʰìŋ", "roman": "cho ching", charclass: "h" },
 {id: 10, character: "ช", "phonetic": "ʨʰɔː ʨʰáːŋ", "roman": "cho chang", charclass: "l" },
 {id: 11, character: "ซ", "phonetic": "sɔː sôː", "roman": "so so", charclass: "l" },
 {id: 12, character: "ฌ", "phonetic": "ʨʰɔː (kà)ʨʰɤː", "roman": "cho choe", charclass: "l" },
 {id: 13, character: "ญ", "phonetic": "jɔː jǐŋ", "roman": "yo ying", charclass: "l" },
 {id: 14, character: "ฎ", "phonetic": "dɔː ʨʰádaː", "roman": "do chada", charclass: "m" },
 {id: 15, character: "ฏ", "phonetic": "tɔː pàtàk", "roman": "dto patak", charclass: "m" },
 {id: 16, character: "ฐ", "phonetic": "tʰɔ̌ː tʰǎːn", "roman": "tho than", charclass: "h" },
 {id: 17, character: "ฑ", "phonetic": "tʰɔː montʰoː", "roman": "tho montho", charclass: "l" },
 {id: 18, character: "ฒ", "phonetic": "tʰɔː pʰûː tʰâw", "roman": "tho puthao", charclass: "l" },
 {id: 19, character: "ณ", "phonetic": "nɔː neːn", "roman": "no nen", charclass: "l" },
 {id: 20, character: "ด", "phonetic": "dɔː dèk", "roman": "do dek", charclass: "m" },
 {id: 21, character: "ต", "phonetic": "tɔː tàw", "roman": "dto tao", charclass: "m" },
 {id: 22, character: "ถ", "phonetic": "tʰɔ̌ː tʰǔŋ", "roman": "tho thung", charclass: "h" },
 {id: 23, character: "ท", "phonetic": "tʰɔː tʰáhǎːn", "roman": "tho thahan", charclass: "l" },
 {id: 24, character: "ธ", "phonetic": "tʰɔː tʰoŋ", "roman": "tho thong", charclass: "l" },
 {id: 25, character: "น", "phonetic": "nɔː nǔː", "roman": "no nu", charclass: "l" },
 {id: 26, character: "บ", "phonetic": "bɔː bajmáj", "roman": "bo baimai", charclass: "m" },
 {id: 27, character: "ป", "phonetic": "pɔː plaː", "roman": "po pla", charclass: "m" },
 {id: 28, character: "ผ", "phonetic": "pʰɔ̌ː pʰɯ̂ŋ", "roman": "pho phueng", charclass: "h" },
 {id: 29, character: "ฝ", "phonetic": "fɔ̌ː fǎː", "roman": "fo fa", charclass: "h" },
 {id: 30, character: "พ", "phonetic": "pʰɔː pʰaːn", "roman": "pho phan", charclass: "l" },
 {id: 31, character: "ฟ", "phonetic": "fɔː fan", "roman": "fo fan", charclass: "l" },
 {id: 32, character: "ภ", "phonetic": "pʰɔː sǎmpʰaw", "roman": "pho samphao", charclass: "l" },
 {id: 33, character: "ม", "phonetic": "mɔː máː", "roman": "mo ma", charclass: "l" },
 {id: 34, character: "ย", "phonetic": "jɔː ják", "roman": "yo yak", charclass: "l" },
 {id: 35, character: "ร", "phonetic": "rɔː rɯːa", "roman": "ro ruea", charclass: "l" },
 {id: 36, character: "ล", "phonetic": "lɔː liŋ", "roman": "lo ling", charclass: "l" },
 {id: 37, character: "ว", "phonetic": "wɔː wɛ̌ːn", "roman": "wo waen", charclass: "l" },
 {id: 38, character: "ศ", "phonetic": "sɔ̌ː sǎːlaː", "roman": "so sala", charclass: "h" },
 {id: 39, character: "ษ", "phonetic": "sɔ̌ː rɯːsǐː", "roman": "so ruesi", charclass: "h" },
 {id: 40, character: "ส", "phonetic": "sɔ̌ː sɯ̌ːa", "roman": "so suea", charclass: "h" },
 {id: 41, character: "ห", "phonetic": "hɔ̌ː hìːp", "roman": "ho hip", charclass: "h" },
 {id: 42, character: "ฬ", "phonetic": "lɔː ʨùlaː", "roman": "lo chula", charclass: "l" },
 {id: 43, character: "อ", "phonetic": "ʔɔː ʔàːŋ", "roman": "o ang", charclass: "m" },
 {id: 44, character: "ฮ", "phonetic": "hɔː nók hûːk", "roman": "ho nokhug", charclass: "l" }
];

export const PHONETICS: String[] = [
 "b","c","d","f","g","h","k","l","m","n","o","p","r","s","t","w","y"];
